messagescan=no
hd=default,vdbench=/root/vdbench,user=root,shell=ssh
hd=hd1,system=localhost

sd=sd1,hd=hd1,lun=/dev/bcache0,openflags=o_direct,threads=32

wd=wd1,sd=sd1,rdpct=0,xfersize=4k,seekpct=100
rd=rd1,wd=wd1,iorate=max,fwd=yes,interval=30,elapsed=172800
